# Generated by Django 3.2.7 on 2021-11-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='image',
            new_name='qr_code',
        ),
    ]
