# Generated by Django 3.2.7 on 2022-01-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_image_joblisting_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Any', 'Any')], max_length=30, null=True),
        ),
    ]
