# Generated by Django 3.2.7 on 2022-01-21 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_joblisting_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='job',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ApplyJobs', to='jobs.joblisting'),
        ),
    ]
