# Generated by Django 3.2.7 on 2022-02-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_applyjob_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='jobname',
            field=models.CharField(blank=True, max_length=100, null='Job Prueba'),
        ),
    ]
