# Generated by Django 3.2.7 on 2022-02-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_applyjob_jobname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='jobname',
        ),
    ]
