# Generated by Django 3.2.7 on 2022-04-05 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
