# Generated by Django 3.2.7 on 2022-04-05 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0004_auto_20210923_1659'),
        ('education', '0002_auto_20210923_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('birthday', models.DateField(verbose_name='Fecha Nacimiento')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Telefono')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('coordinates', models.CharField(blank=True, help_text='Distrito,cantón', max_length=64)),
                ('salary_min', models.IntegerField(blank=True, help_text='₡', null=True, verbose_name='Salario Minimo')),
                ('job_type', models.CharField(blank=True, choices=[('En sitio', 'En sitio'), ('Remoto', 'Remoto'), ('En sitio o Remoto', 'En sitio o Remoto')], max_length=32, verbose_name='Preferencia de empleo')),
                ('type_of_contract', models.CharField(blank=True, choices=[('Contrato', 'Contrato'), ('Permanente', 'Permanente'), ('Contrato o Permanente', 'Contrato o Permanente')], max_length=32, verbose_name='Tipo de Contrato')),
                ('Createresumen', models.FileField(blank=True, null=True, upload_to='Resumenpostulantes', verbose_name='Cargar Curriculum')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_Profile',
                'verbose_name_plural': 'User_Profile',
            },
        ),
        migrations.CreateModel(
            name='UserURL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('network', models.CharField(choices=[('Web', 'Web'), ('Github', 'Github'), ('Bitbucket', 'Bitbucket'), ('Gitlab', 'Gitlab'), ('Twitter', 'Twitter'), ('StackOverflow', 'StackOverflow'), ('Linkedin', 'Linkedin'), ('Youtube', 'Youtube'), ('Facebook', 'Facebook')], max_length=32)),
                ('url', models.CharField(max_length=64)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'verbose_name': 'User Url',
                'verbose_name_plural': 'User Urls',
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('title', models.CharField(max_length=128, verbose_name='Title or resume')),
                ('url', models.CharField(blank=True, max_length=256, verbose_name='Online URL, app store link')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('description', models.TextField(help_text='Describe the software or feature and what your contribution was.')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release date')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'verbose_name': 'User_Project',
                'verbose_name_plural': 'User_Projects',
                'ordering': ('-release_date',),
            },
        ),
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('title', models.CharField(max_length=64, verbose_name='Titulo')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Finalizacion')),
                ('in_progress', models.BooleanField(default=False, verbose_name='En Progreso')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.organization')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'ordering': ('start_date', 'end_date'),
            },
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('title', models.CharField(max_length=64, verbose_name='Grado')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Finalizacion')),
                ('in_progress', models.BooleanField(default=False, verbose_name='En Progreso')),
                ('description', models.TextField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.institution')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_education', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ('-start_date', '-end_date'),
            },
        ),
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=64, verbose_name='Certificado')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Finalizacion')),
                ('in_progress', models.BooleanField(default=False, verbose_name='En Progreso')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.certification')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Certificaciónes',
                'verbose_name_plural': 'Certificaciónes',
                'ordering': ('-start_date', '-end_date'),
            },
        ),
    ]
