# Generated by Django 3.2.7 on 2022-04-18 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usereducation_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducation',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Education', to='users.userprofile'),
        ),
    ]
