# Generated by Django 3.2.7 on 2021-09-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210923_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercertification',
            options={'ordering': ('-start_date', '-end_date'), 'verbose_name': 'Certificaciónes', 'verbose_name_plural': 'Certificaciónes'},
        ),
        migrations.AlterModelOptions(
            name='usereducation',
            options={'ordering': ('-start_date', '-end_date'), 'verbose_name': 'Educación', 'verbose_name_plural': 'Educación'},
        ),
        migrations.AlterModelOptions(
            name='userjob',
            options={'ordering': ('-start_date', '-end_date'), 'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Informacion de usuario', 'verbose_name_plural': 'Informacion de usuarios'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Createresumen',
            field=models.FileField(blank=True, null=True, upload_to='Resumenpostulantes', verbose_name='Cargar Curriculum'),
        ),
        migrations.AlterField(
            model_name='usercertification',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Finalizacion'),
        ),
        migrations.AlterField(
            model_name='usercertification',
            name='in_progress',
            field=models.BooleanField(default=False, verbose_name='En Progreso'),
        ),
        migrations.AlterField(
            model_name='usercertification',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Certificado'),
        ),
        migrations.AlterField(
            model_name='usercertification',
            name='start_date',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Finalizacion'),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='in_progress',
            field=models.BooleanField(default=False, verbose_name='En Progreso'),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='start_date',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Grado'),
        ),
        migrations.AlterField(
            model_name='userjob',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Finalizacion'),
        ),
        migrations.AlterField(
            model_name='userjob',
            name='in_progress',
            field=models.BooleanField(default=False, verbose_name='En Progreso'),
        ),
        migrations.AlterField(
            model_name='userjob',
            name='start_date',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='userjob',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Titulole'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_type',
            field=models.CharField(blank=True, choices=[('En sitio', 'En sitio'), ('Remoto', 'Remoto'), ('En sitio o Remoto', 'En sitio o Remoto')], max_length=32, verbose_name='Preferencia de empleo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='salary_min',
            field=models.IntegerField(blank=True, help_text='₡', null=True, verbose_name='Salario Minimo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type_of_contract',
            field=models.CharField(blank=True, choices=[('Contrato', 'Contrato'), ('Permanente', 'Permanente'), ('Contrato o Permanente', 'Contrato o Permanente')], max_length=32, verbose_name='Tipo de Contrato'),
        ),
    ]
