# Generated by Django 3.2.7 on 2021-10-15 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0002_auto_20210923_1659'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0004_auto_20210923_1659'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('birthday', models.DateField(verbose_name='Fecha Nacimiento')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Telefono')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('coordinates', models.CharField(blank=True, help_text='lat,lon', max_length=64)),
                ('salary_min', models.IntegerField(blank=True, help_text='₡', null=True, verbose_name='Salario Minimo')),
                ('job_type', models.CharField(blank=True, choices=[('En sitio', 'En sitio'), ('Remoto', 'Remoto'), ('En sitio o Remoto', 'En sitio o Remoto')], max_length=32, verbose_name='Preferencia de empleo')),
                ('type_of_contract', models.CharField(blank=True, choices=[('Contrato', 'Contrato'), ('Permanente', 'Permanente'), ('Contrato o Permanente', 'Contrato o Permanente')], max_length=32, verbose_name='Tipo de Contrato')),
                ('Createresumen', models.FileField(blank=True, null=True, upload_to='Resumenpostulantes', verbose_name='Cargar Curriculum')),
                ('Group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informacion de usuario',
                'verbose_name_plural': 'Informacion de usuarios',
            },
        ),
        migrations.CreateModel(
            name='UserURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('Web', 'Web'), ('Github', 'Github'), ('Bitbucket', 'Bitbucket'), ('Gitlab', 'Gitlab'), ('Twitter', 'Twitter'), ('StackOverflow', 'StackOverflow'), ('Linkedin', 'Linkedin'), ('Youtube', 'Youtube'), ('Facebook', 'Facebook')], max_length=32)),
                ('url', models.CharField(max_length=64, verbose_name='Profile url or Username')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoprofile.userprofile')),
            ],
            options={
                'verbose_name': 'User Url',
                'verbose_name_plural': 'User Urls',
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title or resume')),
                ('url', models.CharField(blank=True, max_length=256, verbose_name='Online URL, app store link')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('description', models.TextField(help_text='Describe the software or feature and what your contribution was.')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release date')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoprofile.userprofile')),
            ],
            options={
                'verbose_name': 'User Project',
                'verbose_name_plural': 'User Projects',
                'ordering': ('-release_date',),
            },
        ),
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Titulole')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Finalizacion')),
                ('in_progress', models.BooleanField(default=False, verbose_name='En Progreso')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.organization')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoprofile.userprofile')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'ordering': ('-start_date', '-end_date'),
            },
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Grado')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Finalizacion')),
                ('in_progress', models.BooleanField(default=False, verbose_name='En Progreso')),
                ('description', models.TextField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.institution')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_education', to='infoprofile.userprofile')),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Educación',
                'ordering': ('-start_date', '-end_date'),
            },
        ),
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Certificado')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Finalizacion')),
                ('in_progress', models.BooleanField(default=False, verbose_name='En Progreso')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.certification')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoprofile.userprofile')),
            ],
            options={
                'verbose_name': 'Certificaciónes',
                'verbose_name_plural': 'Certificaciónes',
                'ordering': ('-start_date', '-end_date'),
            },
        ),
    ]
